### ISSUE TITLE
can´t display the playlist

### ISSUE THREAD

**Issue by jrcorralesf** [CleverProgrammers/spotify-clone#14]
I try to fix it by changing the line with playlist to -> playlists:playlists but it doesn´t work, any help?

 spotify.getUserPlaylists().then((playlists) => {
        dispatch({
          type: "SET_PLAYLISTS",
          playlists,  
        });
      });

**Comment by jrcorralesf** [comment]
EDIT:
i solve this by adding the scopes playlist-read-collaborative and playlist-read-private in the spotify.js

const scopes = [
"user-read-currently-playing",
"user-read-recently-played",
"user-read-playback-state",
"user-top-read",
"user-modify-playback-state",
"playlist-read-private",
"playlist-read-collaborative",
];

More info: https://developer.spotify.com/documentation/general/guides/scopes/

**Comment by mynk-s-rwt** [comment]
I don't know why .. my playlist is still returning 0 array items?
You know why?

**Comment by mic7x4** [comment]
> I don't know why .. my playlist is still returning 0 array items?
> You know why?

Same here brother I can't find what is wrong been 2days

**Comment by jrcorralesf** [comment]
> I don't know why .. my playlist is still returning 0 array items?
> You know why?
