### ISSUE TITLE
unable to deploy this application via firebase 

### ISSUE THREAD

**Issue by ankushchk** [CleverProgrammers/spotify-clone#21]
![1604933636544](https://user-images.githubusercontent.com/67872399/98556890-8e884c00-22c9-11eb-9361-7b1eb0332053.png)

**I also changes the redirect url to deployed app url and afterwards this is also not working** 

-  **It throw me back to this information**

![1604934027997](https://user-images.githubusercontent.com/67872399/98558154-16bb2100-22cb-11eb-9a5f-c5e12f192821.png)

![Capture](https://user-images.githubusercontent.com/67872399/98633667-e1084d80-2347-11eb-9d61-331d7829f8e8.PNG)

**Comment by D-March** [comment]
Change the redirectUri value to the domain for the app on firebase (e.g. app-name-1234.web.app) and then add that domain to your redirect URIs on the Spotify developer dashboard and it should work.

**Comment by ankushchk** [comment]
![mIN](https://user-images.githubusercontent.com/67872399/99288044-0d006300-2861-11eb-86fc-bbfffa455577.png)

**Got it !!!!**
