### ISSUE TITLE
Getting 403 error while clicking on play button and shuffle button

### ISSUE THREAD

**Issue by iambherulal** [CleverProgrammers/spotify-clone#30]
https://api.spotify.com/v1/me/player/play
{
error: {
status: 401,
message: "No token provided"
}
}
![image](https://user-images.githubusercontent.com/43438745/115796732-fb168380-a3ef-11eb-8768-b300692a7f08.png)

**Comment by malikhamza-v** [comment]
I'm getting the same issue. Did you get the solution??

**Comment by iambherulal** [comment]
No, I haven't gotten chance to check after that
